/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as PresentSessionIdRouteImport } from './routes/present.$sessionId'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SessionSessionIdStatsRouteImport } from './routes/session.$sessionId_.stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentSessionIdRoute = PresentSessionIdRouteImport.update({
  id: '/present/$sessionId',
  path: '/present/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdStatsRoute = SessionSessionIdStatsRouteImport.update({
  id: '/session/$sessionId_/stats',
  path: '/session/$sessionId/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/stats': typeof SessionSessionIdStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId/stats': typeof SessionSessionIdStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/present/$sessionId': typeof PresentSessionIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/$sessionId_/stats': typeof SessionSessionIdStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/present/$sessionId'
    | '/session/$sessionId'
    | '/session/$sessionId/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/present/$sessionId'
    | '/session/$sessionId'
    | '/session/$sessionId/stats'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/present/$sessionId'
    | '/session/$sessionId'
    | '/session/$sessionId_/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  PresentSessionIdRoute: typeof PresentSessionIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionSessionIdStatsRoute: typeof SessionSessionIdStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$sessionId': {
      id: '/present/$sessionId'
      path: '/present/$sessionId'
      fullPath: '/present/$sessionId'
      preLoaderRoute: typeof PresentSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId_/stats': {
      id: '/session/$sessionId_/stats'
      path: '/session/$sessionId/stats'
      fullPath: '/session/$sessionId/stats'
      preLoaderRoute: typeof SessionSessionIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  PresentSessionIdRoute: PresentSessionIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionSessionIdStatsRoute: SessionSessionIdStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
